### ISSUE TITLE
Doesn't support hinting 

### ISSUE THREAD

**Issue by matanbanin** [Python-Optional/optional.py#34]
Which is pretty crucial on a wrap of an object, i couldn't use it that way...

**Comment by cbefus** [comment]
Type hinting was introduced in python 3.5 and continues to evolve.  Due to our goal of supporting as many python versions as possible, type hinting has taken a backseat.  We will continue to watch for a way to backport type hints of generics through all supported versions of python and reevaluate.

That being said, this is open source and we are very open to contribution, so feel free to open a PR.

**Comment by matanbanin** [comment]
How can i implement it on python>=3.5 and that it will still be backward compatible?

**Comment by cbefus** [comment]
@matanbanin Yes that is my struggle too! If you look at the PR I made above I tried adding them in a way that works for all versions of Python but the hinting doesnt seem 100% correct.  Feel free to pull that branch as a initial starting point!

**Comment by matanbanin** [comment]
I can't create a new branch, so i'll post my code here optional.py

It seems to work on my python, is this code compatible on older versions?


from typing import Any, TypeVar, Generic

from optional.abstract_optional import AbstractOptional
from .nothing import Nothing
from .something import Something

T = TypeVar('T')


class Optional(Generic[T]):
    @classmethod
    def of(cls, thing: T = None) -> AbstractOptional[T]:
        return Nothing(cls) if thing is None else Something(thing, cls)

    @classmethod
    def empty(cls):
        # type: () -> 'Nothing'
        return Nothing(cls)


int = Optional.of(1)
int.get()

**Comment by cbefus** [comment]
Unfortunately, what you did above is not completely backwards compatible.  Pre 3.5 versions of python only accept the comment style of hints so your line:
```python
def of(cls, thing: T = None) -> AbstractOptional[T]:
```
would cause problems due to both the `: T = None` and the `-> AbstractOptional[T]`.  

I made a branch called `Typing` which is close.  @dpassen might get a chance to review it this weekend.

**Comment by matanbanin** [comment]
from typing import Any, TypeVar, Generic

from optional.abstract_optional import AbstractOptional
from .nothing import Nothing
from .something import Something

T = TypeVar('T')


class Optional(Generic[T]):
    @classmethod
    def of(cls, thing= None):
        # type: (T) -> AbstractOptional[T]
        return Nothing(cls) if thing is None else Something(thing, cls)

    @classmethod
    def empty(cls):
        # type: () -> 'Nothing'
        return Nothing(cls)


int = Optional.of(1)
int.get()

And this?

**Comment by matanbanin** [comment]
?

**Comment by cbefus** [comment]
@dpassen this is solved by new version right?

**Comment by dpassen** [comment]
Using pyright language server, this is what I see using the lib:
<img width="257" alt="image" src="https://github.com/Python-Optional/optional.py/assets/997822/5c31c60c-c861-4802-8983-7c52f3328b8c">

**Comment by cbefus** [comment]
lgtm closing
